spring:
  application:
    name: cloudProvide

server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8760/eureka/,http://localhost:8762/eureka/
  instance:
    instance-id: provider-8002
#    prefer-ip-address: true
info:
  app.name: Demo

