spring:
  application:
    name: cloudProvide

server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8762/eureka/,http://localhost:8761/eureka/
  instance:
    instance-id: provider-8003
#    prefer-ip-address: true
info:
  app.name: Demo-8003

