server:
  port: 9527

spring:
  application:
    name: cloudZuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8760/eureka/
  instance:
    instance-id: cloud-zuul
#访问地址原本是http://localhost:9527/cloudprovide/demo
zuul:
#  prefix配置前缀
#  prefix: /lj
  routes:
    cloudprovide: /provide/**
  ignored-services: '*'
#  ignored-services: cloudprovide
